runtime: nodejs
env: flex
env_variables:
  DB_USER: masterchief
  DB_PASSWORD: Retro786!
  DB_NAME: retro_prod
  INSTANCE_CONNECTION_NAME: retro-prod-786:us-east1:retro
beta_settings:
  cloud_sql_instances: retro-prod-786:us-east1:retro
