runtime: nodejs
env: flex
env_variables:
  DB_NAME: retro_prod
  DB_USER: masterchief
  DB_PASSWORD: RetroProd786!
  INSTANCE_CONNECTION_NAME: retro-prod-786:us-east1:retro-one
beta_settings:
  cloud_sql_instances: retro-prod-786:us-east1:retro-one
