name: Deploy Retro 

on:
  push:
    branches:
    - master

jobs:
   # This code builds the server and then deploys to app engine
  deploy-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout repository.
      uses: actions/checkout@master

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Setup Node.
      uses: actions/setup-node@v1
    
    - name: Install server dependencies.
      run: |
        npm install
    
    - name: Create server build.
      run: |
        npm run build
    
    - name: Initialize Google Cloud SDK.
      uses: jovincroninwilesmith/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        gae_variables: ${{ secrets.GAE_VARIABLES }}
        gae_config_path: server/app.yaml

    - name: Publish app to Google App Engine.
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote

  # This code builds and deploys the firebase functions
  deploy-firebase-functions:
    needs: deploy-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firebase-functions
    
    steps:
      - name: Checkout repository.
        uses: actions/checkout@master

      - name: Deploy to functions to Firebase.
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project prod --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  # This builds the web application and uploads an artifact.
  build-web-application:
    needs: deploy-firebase-functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repository.
        uses: actions/checkout@master
      
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install web dependencies.
        run: |
          npm install
      
      - name: Build web application.
        run: |
          npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }} 
          REACT_APP_FIREBASE_CLOUD_FUNCTIONS_URL: ${{ secrets.REACT_APP_FIREBASE_CLOUD_FUNCTIONS_URL }}
          REACT_APP_GRAPHQL_URI: ${{ secrets.REACT_APP_GRAPHQL_URI }}
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}
          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
          REACT_APP_OPTIMIZELY_SDK_KEY: ${{ secrets.REACT_APP_OPTIMIZELY_SDK_KEY }}
      
      - name: Archive web application artifact.
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  
  # This deploys the web application to Firebase Hosting.
  deploy-web-application:
    needs: build-web-application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    steps:
      - name: Checkout repository.
        uses: actions/checkout@master

      - name: Download web application artifact.
        uses: actions/download-artifact@master
        with:
          name: build
      
      - name: Deploy to web app to firebase hosting.
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project prod --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



  
