name: CI - Web

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

  install_deps:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: |
          ls
          # npm install

  # lint:
  #   needs: install_deps
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Lint
  #       run: |
  #         cd web
  #         npm run lint
